// ─── Network & Contract Configuration ──────────────────────────────────────

/**
 * Arbitrum Sepolia — the testnet where our contract is deployed.
 * To get free test ETH, visit: https://faucet.triangleplatform.com/arbitrum/sepolia
 */
export const SUPPORTED_CHAIN = {
  id: 421614,
  name: "Arbitrum Sepolia",
  // publicnode is more reliable than the official endpoint for free usage
  rpcUrl: "https://arbitrum-sepolia-rpc.publicnode.com",
  rpcFallback: "https://sepolia-rollup.arbitrum.io/rpc",
  blockExplorer: "https://sepolia.arbiscan.io",
  currency: "ETH",
  cofheNetwork: "arb-sepolia" as const,
};

// Auto-generated by contracts/scripts/deploy.ts — update after redeploying
export { CONTRACT_ADDRESS } from "./deployedAddress";
